<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zving</groupId>
        <artifactId>content-security</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>plugin-content-security</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.zving</groupId>
            <artifactId>framework</artifactId>
            <version>4.0.7-rc2</version>
        </dependency>
        <dependency>
            <groupId>com.zving</groupId>
            <artifactId>plugin-platform</artifactId>
            <version>4.0.5-rc2</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.zving</groupId>
                <artifactId>zving-maven-plugin</artifactId>
                <version>${zving.maven.plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
